name: Build and Deploy Production

on:
  push:
    branches:
      - "prod"
  workflow_dispatch:
  workflow_run:
    workflows: ["On Publish Tag"]
    types:
      - completed

permissions:
  contents: read

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy-template.yml@main
    with:
      environment: prod
      branch: prod